filebeat.inputs:
  - type: filestream
    id: app-stack-id
    paths:
      - /logs/*.log

filebeat.modules:
  - module: nginx
    access:
      enabled: true
      var.paths: ["/logs/access.log"]
    error:
      enabled: true
      var.paths: [ "/logs/error.log" ]

setup.kibana:
  host: ""

output.elasticsearch:
  hosts: ""
  username: ""
  password: ""
